# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SwiftPlayer_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPlayer_Example
  # pod "SwiftPlayer", :path => '../'
  pod "ObjectMapper", "~> 3.5.0"
  pod "AlamofireImage", "~> 4.0.0"

  # target 'SwiftPlayer_Tests' do 
  #   # Pods for Tests
  #   inherit! :search_paths
  # end

end

