# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftPlayer_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPlayer_Example
  pod 'SwiftPlayer', :path => '../'
  pod "ObjectMapper", "~> 1.1"
  pod "AlamofireImage", "~> 2.3"

end